### PR TITLE
adding child information

### PR DESCRIPTION
**Pull request by bgroover**

### CODE REVIEW

**Comment by bgroover** [comment]
Hey Mitch, Cory gave me some of the work he did. I am going to try to github it over to you. What program would you like to use to video chat for next week?

Brandon 

    On Wednesday, May 4, 2016 9:18 PM, Mitch Mullvain <notifications@github.com> wrote:
 

 Merged #2.—

**Comment by bgroover** [comment]
How do i transfer files to Git hub? 

    On Monday, May 16, 2016 4:51 PM, brandon groover <bg2532@yahoo.com> wrote:
 

 Hey Mitch, Cory gave me some of the work he did. I am going to try to github it over to you. What program would you like to use to video chat for next week?

Brandon 

    On Wednesday, May 4, 2016 9:18 PM, Mitch Mullvain <notifications@github.com> wrote:
 

 Merged #2.—

**Comment by RaptorJesus67** [comment]
I believe you "push" them. Either that or "fork". Worse case, send them to
me via email.
On May 17, 2016 3:23 PM, "bgroover" <notifications@github.com> wrote:

How do i transfer files to Git hub?

On Monday, May 16, 2016 4:51 PM, brandon groover <bg2532@yahoo.com> wrote:


Hey Mitch, Cory gave me some of the work he did. I am going to try to
github it over to you. What program would you like to use to video chat for
next week?

Brandon

On Wednesday, May 4, 2016 9:18 PM, Mitch Mullvain <notifications@github.com>
wrote:


Merged #2.—
You are receiving this because you authored the thread.

Reply to this email directly or view it on GitHub



—
You are receiving this because you modified the open/close state.

Reply to this email directly or view it on GitHub
<https://github.com/RaptorJesus67/daycare/pull/2#issuecomment-219872414>

**Comment by bgroover** [comment]
i'll attach the files over email. 

    On Tuesday, May 17, 2016 6:21 PM, Mitch Mullvain <notifications@github.com> wrote:
 

 I believe you "push" them. Either that or "fork". Worse case, send them to
me via email.
On May 17, 2016 3:23 PM, "bgroover" <notifications@github.com> wrote:

How do i transfer files to Git hub?

On Monday, May 16, 2016 4:51 PM, brandon groover <bg2532@yahoo.com> wrote:


Hey Mitch, Cory gave me some of the work he did. I am going to try to
github it over to you. What program would you like to use to video chat for
next week?

Brandon

On Wednesday, May 4, 2016 9:18 PM, Mitch Mullvain <notifications@github.com>
wrote:


Merged #2.—
You are receiving this because you authored the thread.

Reply to this email directly or view it on GitHub



—
You are receiving this because you modified the open/close state.

Reply to this email directly or view it on GitHub
<https://github.com/RaptorJesus67/daycare/pull/2#issuecomment-219872414>
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub  

  
<!DOCTYPE html>
<html>
<body>
</body>
</html>

**Comment by RaptorJesus67** [comment]
Try to do it today or tomorrow. I want to have a rough draft of it done by
Tuesday.

**Comment by bgroover** [comment]
i attached the files in my previous email. Cory said that he is working on the CSS and will add it later.

    On Wednesday, May 18, 2016 2:58 PM, Mitch Mullvain <notifications@github.com> wrote:
 

 Try to do it today or tomorrow. I want to have a rough draft of it done by
Tuesday.

**Comment by RaptorJesus67** [comment]
I don't have the files, try sending them again please.

**Comment by bgroover** [comment]
attached files from Cory. 

    On Friday, May 20, 2016 12:54 PM, Mitch Mullvain <notifications@github.com> wrote:
 

 I don't have the files, try sending them again please.

On Wed, May 18, 2016 at 4:16 PM, bgroover <notifications@github.com> wrote:

> i attached the files in my previous email. Cory said that he is working on
> the CSS and will add it later.
>
> On Wednesday, May 18, 2016 2:58 PM, Mitch Mullvain <
> notifications@github.com> wrote:
>
>
> Try to do it today or tomorrow. I want to have a rough draft of it done by
> Tuesday.
>
> On Tue, May 17, 2016 at 5:46 PM, bgroover <notifications@github.com>
> wrote:
>
> > i'll attach the files over email.
> >
> > On Tuesday, May 17, 2016 6:21 PM, Mitch Mullvain <
> notifications@github.com>
> > wrote:
> >
> >
> > I believe you "push" them. Either that or "fork". Worse case, send them
> to
> > me via email.
> > On May 17, 2016 3:23 PM, "bgroover" <notifications@github.com> wrote:
> >
> > How do i transfer files to Git hub?
> >
> > On Monday, May 16, 2016 4:51 PM, brandon groover <bg2532@yahoo.com>
> wrote:
> >
> >
> > Hey Mitch, Cory gave me some of the work he did. I am going to try to
> > github it over to you. What program would you like to use to video chat
> for
> > next week?
> >
> > Brandon
> >
> > On Wednesday, May 4, 2016 9:18 PM, Mitch Mullvain <
> > notifications@github.com>
> > wrote:
> >
> >
> > Merged #2.—
> > You are receiving this because you authored the thread.
> >
> > Reply to this email directly or view it on GitHub
> >
> >
> >
> > —
> > You are receiving this because you modified the open/close state.
> >
> > Reply to this email directly or view it on GitHub
> > <https://github.com/RaptorJesus67/daycare/pull/2#issuecomment-219872414>
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
> >
> > <!DOCTYPE html>
> > <html>
> > <body>
> > </body>
> > </html>
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/RaptorJesus67/daycare/pull/2#issuecomment-219895811>
> >
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/RaptorJesus67/daycare/pull/2#issuecomment-220185873>
>
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub  

  
<!DOCTYPE html>
<html>
<body>
</body>
</html>

**Comment by RaptorJesus67** [comment]
Yeah it's not doing it via GitHub.

Send an actual email with them attached to me at:

experienceit12@gmail.com

**Comment by bgroover** [comment]
ok i sent the files to your email. 

    On Saturday, May 21, 2016 1:28 PM, Mitch Mullvain <notifications@github.com> wrote:
 

 Yeah it's not doing it via GitHub.

Send an actual email with them attached to me at:

experienceit12@gmail.com

**Pull request merged**
